version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feedbackreportgenerator
  redis:
    image: redis:alpine
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: poetry run celery -A feedbackreportgenerator worker --loglevel=info
    depends_on:
      - db
      - redis
  flower:
    image: mher/flower
    command: flower --broker=redis://redis:6379
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data:
